name: Build and Deploy Astro site

on:
  push:
    branches:
      - main   # or your default branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'   # or your preferred Node version

    - name: Install dependencies
      run: npm install
      working-directory: ./site   # adjust if your Astro project is inside a folder

    - name: Build site
      run: npm run build
      working-directory: ./site

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site/dist
        publish_branch: gh-pages
        cname: opensourcemech.com
        user_name: github-actions
        user_email: github-actions@github.com
